DROP TABLE USERS CASCADE CONSTRAINTS PURGE;

CREATE TABLE USERS (
  USER_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  FULL_NAME    VARCHAR2(100)   NOT NULL,
  EMAIL        VARCHAR2(120)   NOT NULL UNIQUE,
  GENDER       CHAR(1)         CHECK (GENDER IN ('M','F','O')),
  DOB          DATE,
  HEIGHT_CM    NUMBER(5,2),
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP
);

-- Drop old table and constraints
DROP TABLE EXERCISE CASCADE CONSTRAINTS PURGE;

-- Recreate EXERCISE with identity starting at 1
CREATE TABLE EXERCISE (
  EXERCISE_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  NAME         VARCHAR2(80)  NOT NULL UNIQUE,
  CATEGORY     VARCHAR2(40)  CHECK (CATEGORY IN ('Strength','Cardio','Flexibility','Balance','Other')),
  UNIT         VARCHAR2(20)  CHECK (UNIT IN ('reps','minutes','km','kg','calories','meters','steps','other')),
  MET_VALUE    NUMBER(4,2)   -- optional for cardio calorie est.
);

-- -----------------------------------------------------------------------------------------------------

SHOW USER;



COMMIT;




-- First truncate child tables
TRUNCATE TABLE SLEEP_LOG;
TRUNCATE TABLE BODY_METRICS;
TRUNCATE TABLE GOAL;
TRUNCATE TABLE NUTRITION_LOG;
TRUNCATE TABLE WORKOUT_EXERCISE;
TRUNCATE TABLE WORKOUT_SESSION;

-- Then truncate master tables
TRUNCATE TABLE EXERCISE;
TRUNCATE TABLE USERS;


-- -----------------------------------------------------------------------------------------------------

    INSERT INTO USERS (FULL_NAME, EMAIL, GENDER, DOB, HEIGHT_CM) 
    VALUES ('Artemis Garth', 'artemis.garth@gmail.com', 'F', DATE '2003-07-26', 165.5);

    INSERT INTO USERS (FULL_NAME, EMAIL, GENDER, DOB, HEIGHT_CM) 
    VALUES ('Unity Garth', 'unity.garth@gmail.com', 'F', DATE '2005-02-18', 165.0);

    INSERT INTO USERS (FULL_NAME, EMAIL, GENDER, DOB, HEIGHT_CM) 
    VALUES ('Maximous Black', 'maximousblk@gmail.com', 'M', DATE '1995-01-15', 182.2);


-- -----------------------------------------------------------------------------------------------------
-- Strength
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Push Ups', 'Strength', 'reps', 8.0);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Squats', 'Strength', 'reps', 7.0);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Bench Press', 'Strength', 'kg', 6.0);

-- Cardio
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Running', 'Cardio', 'km', 9.8);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Walking', 'Cardio', 'km', 3.8);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Cycling', 'Cardio', 'minutes', 7.5);

-- Flexibility
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Yoga', 'Flexibility', 'minutes', 3.0);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Stretching', 'Flexibility', 'minutes', 2.5);

-- Balance
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Plank', 'Balance', 'minutes', 3.3);
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Single-leg Stand', 'Balance', 'minutes', 2.8);

-- Other
INSERT INTO EXERCISE (NAME, CATEGORY, UNIT, MET_VALUE) VALUES ('Skipping Rope', 'Other', 'minutes', 11.0);

SELECT * FROM USERS;