SHOW CON_NAME;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER FITTRACK CASCADE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -01918 THEN -- user does not exist
    RAISE;
  END IF;
END;
/

CREATE USER FITTRACK IDENTIFIED BY "Fittrack#123"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;


GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW,
       CREATE TRIGGER, CREATE PROCEDURE TO FITTRACK;

GRANT CONNECT, RESOURCE TO FITTRACK;